/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_study_video_VideoUtils */

#ifndef _Included_com_example_study_video_VideoUtils
#define _Included_com_example_study_video_VideoUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_study_video_VideoUtils
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_study_1video_VideoUtils_init
  (JNIEnv *, jclass);

/*
 * Class:     com_example_study_video_VideoUtils
 * Method:    decode
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_com_example_study_1video_VideoUtils_decode
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     com_example_study_video_VideoUtils
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_study_1video_VideoUtils_close
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
